language: node_js
node_js:
- stable
services:
- mongodb
cache:
  npm: false
notifications:
  email: false
script:
- cd server/
- npm ci
- npm test
- npm run coverage
after_success:
- npm run coveralls
branches:
  only:
  - deploy
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: YY325PN4NnyeNjsvI9/zSejPH0D2cDch0xKaC2q8yZ/tkzXdn+3IPTwPDYkcy1D3cTLwfFoICvasqvoMdegcAnfFuHKvLagD1tro1Maqe1fLryvGLavQqfcRS2HZtmcRPCQGCqvkcmwjfxHvqIwJnv9bDVQGy5ySrZN8yDdL2yQgyxoUcvhOpdqfBpk+AW176lebOK9x+wt0meQYXnCC548HfrKXB1GIISVQM+f6FuAsA9+VfN3BnsFjLIh1k3Yw/ePcUIhFTWDN1sfzAEXYN0r0fC2rT9/0sg9khFNNIs2OBUeVRDN7BfnhtjUq+ObyTQ40Ncc0XAvn8oLjzW8X1FwCRN/MDr7w3oE47o5bQWR0Mnnl3u4oa3lhDP3N212dracfu4D/Z4UoBeBtLVfX0tm5eSE58Yp7WfGr1WMxqK9YHTCszdin6Bnwk5jNVf4f+nJiUMjVaYZ3BGb5lwrGXrVIm9A8aGpsakQT60OE8rI5L31i/19beCNIzQy4k/T4hvTiQr6A7DmG7PqvIbAHJH3jVLE2DNmv+EpezqWO3+aEbIuKQLcldwMDP0GN5f9TjebntZK2POC/sC1NMdGhd3eXT2cRMhW7sN1MJiXIBTxPbokAQ/FCEItVQJCNjpbsn6L6lx8Jfb05nB+5OQJaDC17i8PqIG5+p7w4RKmB8Xw=
  app:
    deploy: alainmucyo-staging
