language: node_js
node_js:
- stable
services:
- mongodb
cache:
  npm: false
notifications:
  email: false
script:
- cd server/
- npm ci
- npm test
- npm run coverage
after_success:
- npm run coveralls
branches:
  only:
  - deploy
deploy:
  provider: heroku
  api_key:
    secure: SFrsMOMR+yLz9iaIB+an5qSf0mRJ+nYiOwNabmDgDRiXwh92w9ctYJaMGMc8TNTA1KM4VIqigx9G7VMNQAru/6ZJPVRM2a4PCmQHrQgiRK0NpGlaPZAN9+hXdK6sVcYPtRhcRxTCUEFAtYH15z52kelRKJmuyO4A5k8cqDWNPXQUS2ypPasxATgUHk/wl38Qavhk74/SLPa9Davep3DcFG3LHSkTwN7hn86AeJyor7wPg8z1Nb8zG/sQLx44hizqyi9t+VXTg3gci1PbISGi3jdMB3t3D6DmpHi5qbPk28/x/7ROtP/EX9KrJWyKKwqU60qzJfseFY8dunoasjIAh5HXSVCFLvB2/B1O++uX7x5BM77/STOkOVqvqMLFfE5bv4xJQA71B+4s5mQNlLjQl66SEqZ/fpHYmeOOqVSIPO8xX6//O5dVBLo2CNpSzNualM3tN74ScBsMkINMXx86Zvti9jIUfXhzchqt4RxjXIQa5QhFTm+YKokQ01OGkiaVthlPI+HkOIGNei8DjpMRmnlZ3VfcD+yFPGF4+XA6R+tOZPMyoFCELPZ73rg0P6DzW3HB6vTAu6yuMjqzWio6Bvv9v1hOqLEfiX74a6N8rMPMvhqFBjgsOOib+1LdtyDQeUI8T+/jGHWLY3CFK7/zlrG/Z7SfyU17X3mM1vMI74I=
  app:
    deploy: alainmucyo-staging
