language: node_js
node_js:
- stable
services:
- mongodb
cache:
  npm: false
notifications:
  email: false
script:
- cd server/
- npm ci
- npm test
- npm run coverage
after_success:
- npm run coveralls
branches:
  only:
  - deploy
deploy:
  provider: heroku
  api_key:
    secure: NTEkUL2B0sVl5yPWm3rabUhP4RbfwypG/8K0EkpESm5lGTLZtOg2mBOVQ19ffgvKGprI64mbbRpzbtgZ0SUjgwAqKcIxYcsgq3kM4JLh5Ovs1PYhjlyqhiu6oRiexAcZEIITf9kccMxRlsOiKcLV2xt95tddH5WKtMkYJ6+0nI4Icr9URyJlObE6+OJwtDwD2GPgt0w8kHqqn3JF/iRWQbiYX0Dw1WtlIxSd27PHbMijmty62gH0J0oPZm6L/s01pIZu1wSvtPaog9xGjc0L/SkiDViV2F7ryMf6PpyneOuwS7rvIysBVKjMmpBtvPDHf2V4UpeAQNikVCRox4+KCFpALgcSv15kst9EaYyHmuYYBgtc3lJNNLPrdfDThPkvyaw6gUELYfmsjC2Sc3s5eF/N1bbSTe6fd/19ip1kTLwe3AX/RdtA71pvZLEpTA4IKOd+8F2zi4AMqBhZ9SB0TK4AAG0PXPGlD6r6XOgZVI0uhC+oD78/+SqhS8PHY80YKzXMrwdlWPSovavCIZ7SqR8tspJm7Bkvrd/MFf1+A74VA8Coh/l4h34QWAMl2LAdMi6OXQqWxErvdx6HVQDEOtTSpR29sw8JhHxHTnPqNfKpWgBh5b1YguOpgbU8Tq2yFgfgBZssCaodgRD+LcieRGaHTZ/7jOh60/o3KAJnd+A=
  app:
    deploy: alainmucyo-staging
